### ISSUE TITLE
port and forwardPort must be different

### ISSUE THREAD

**Issue by jdiamond** [sorribas/tcp-spy#7]
If forwardHost is not localhost, can't the ports be the same?

**Comment by sorribas** [comment]
You mean doing something like this?

`tcp-spy 3000 somehost.com`

I think it's a good idea. Something like this could also be supported

`tcp-spy somehost.com:3000 someotherhost.com`

**Comment by jdiamond** [comment]
Those shortcuts seem nice, but I'm using tcp-spy as a module and this line is what I'm referring to:

https://github.com/sorribas/tcp-spy/blob/20026690e0a1011f6d77dbcc0784bb1f9137cf7b/index.js#L11

That restriction doesn't seem necessary if forwardHost is not localhost.

**Comment by sorribas** [comment]
@jdiamond That is true. It should be fixed in version `1.0.0`. Also the error is now emitted instead of thrown.

**Comment by jdiamond** [comment]
Very cool, thank you.
